### ISSUE TITLE
Display compilation failure messages in output

### ISSUE THREAD

**Issue by ndaniels** [thoward27/grade#18]
Currently, unlike the standard Gradescope autograder, when a student's code fails to compile, nothing informative is shown (not even to the instructor). Ideally, the compilation failure (stderr) could be captured and shown (possibly even to the student) as the test output for the compilation check. This would cut down on TA support time, as often it's something as simple as the student forgot their compile script.

**Comment by thoward27** [comment]
@ndaniels it actually appears we were generating output, but Gradescope didn't like it. The spec calls for a string, we were giving a list in that case. Should have a new version with that tweak shortly.

**Comment by ndaniels** [comment]
I’m still not seeing this working properly. Students see something like “AssertionError: sudoku does not exist!” but not the compilation error. Since ssh debugging is also broken, this is a problem.

**Comment by thoward27** [comment]
that error would signify they didn't get to compilation. something about copying the files over went wrong, or the `self.requires` statement isn't configured right.
