### ISSUE TITLE
Grade does not appear to set test-case level visibility correctly.

### ISSUE THREAD

**Issue by Jmdwow** [thoward27/grade#21]
**Describe the bug**
When using the '@visibility' decorator for an individual test case function, nothing is actually changed. The visibility for the whole assignment is still 'visible', while the visibility value for the individual test cases is not output as a part of the JSON file. The attribute appears to be set correctly, but just not included in the JSON output.

**To Reproduce**
1. Decorate a test function with '@visibility('after_due_date)'
2. Call grade run and grade report
3. Look at JSON output for individual test cases

**Expected behavior**
The visibility of an individual test case should show up in the list of properties for that test case in the JSON file.

**Comment by Jmdwow** [comment]
I appear to be running the latest version of grade, if that helps

**Comment by thoward27** [comment]
Fixed in #25
