### ISSUE TITLE
Json output lacking newlines.

### ISSUE THREAD

**Issue by Jmdwow** [thoward27/grade#37]
**Describe the bug**
The json output from grade report is formatted without any newlines.

**To Reproduce**
1. Run an autograder
2. Run grade report --format json

**Expected behavior**
The json output has newlines to easily read the output if needed.

**Comment by thoward27** [comment]
Hey @Jmdwow can you provide the version of grade you're using?

**Comment by Jmdwow** [comment]
It's the most recent. 3.0

**Comment by thoward27** [comment]
@Jmdwow, I'm torn here. `grade` provides `--format gradescope` which is pretty, `json` is not. Do you think that should be flipped? Gradescope doesn't care about it's formatting, but users of `json` may; would you agree?

**Comment by Jmdwow** [comment]
Yeah, I feel like that would be better. Looking at the json output on gradescope, if a test case fails, the error message for that test case is provided on its own, without all of the other information, so the json being formatted and gradescope not sounds like the best solution in my opinion.

**Comment by thoward27** [comment]
Should be good to go in the next release!
